### ISSUE TITLE
Start documenting HuskyCI

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyci#122]

**Comment by mdjunior** [comment]
@rafaveira3 , we started!
Creating page with routes at wiki (https://github.com/globocom/huskyci/wiki/api-routes)

**Comment by mdjunior** [comment]
Page with environment variables: https://github.com/globocom/huskyci/wiki/api-env-var (needs revision and more examples)

**Comment by rafaveira3** [comment]
Thanks, @mdjunior ! We are indeed writing a lot of docs, heh? Closing this for now !
