### ISSUE TITLE
"dockerPullImage(): repository name must be canonical" 

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#145]
When not pulling securityTests containers via Makefile, the following error is being seeing:

`dockerPullImage(): repository name must be canonical`

It would be a good idea to check this function: 

``` 
func (d Docker) PullImage(image string) error {
	ctx := goContext.Background()
	_, err := d.client.ImagePull(ctx, image, dockerTypes.ImagePullOptions{})
	return err
}
```

**Comment by qiangli** [comment]
For your own image, just prepend docker.io/ to the image name.

**Comment by rafaveira3** [comment]
Hey, @qiangli ! Thanks a lot for this tip! I will use your suggestion when working on this issue once again! 👍🏻
