### ISSUE TITLE
Can you run more than one security test on the same language?

### ISSUE THREAD

**Issue by Krlier** [globocom/huskyci#161]
I've developed [Safety security test] to Huskyci, but I'm not able to run it with Bandit. Both tests are for Python.
You can find Safety in [my fork].

Could you please verify that? 

Thanks!

[Safety security test]: https://github.com/pyupio/safety
[my fork]: https://github.com/Krlier/huskyci/tree/Safety

**Comment by rafaveira3** [comment]
Yeah, sure! Thanks for this improvement, @Krlier ! I will reproduce this issue using your branch to check this!
