### ISSUE TITLE
Safety security test is not able to find requirements.txt if it isn't in the project's root directory.

### ISSUE THREAD

**Issue by Krlier** [globocom/huskyCI#179]
If a project's `requirement.txt` isn't in it's root directory, Safety can't find it.

At the time of writing, huskyCI tries to locate the file through the command: `cat *requirements* | grep '=' | grep -v '#' > safety_analysis_requirements.txt 2> /tmp/errorGetRequirements` in `config.yml`.

A possible solution to this problem would be to implement a recursive search.

**Comment by rafaveira3** [comment]
Cool finding! Also, some projects use [setup.py](https://github.com/globocom/gsenha-python/blob/master/setup.py) to install their dependencies. It would be great if we had the chance to check that too!

**Comment by rafaveira3** [comment]
Setting this as a feature because `safety` does not have at this moment a way to handle this. It isnt something wrong that is in huskyCI code.

**Comment by rafaveira3** [comment]
Closing this for now as we huskyCI expects that requirements.txt is into the root folder by default. If not, a warning will be sent to the user.
