### ISSUE TITLE
A bug in one of the queries to MongoDB is causing some of the fields of a securityTest to be overwritten in the database

### ISSUE THREAD

**Issue by Krlier** [globocom/huskyCI#218]
I first came across this issue when trying to run huskyCI without downloading the images right away and using it's built in functionality to fetch them.

A way to observe this issue is that `Enry`'s `cInfo` field is overwritten with blank after the analysis is complete and without any query directly changing the field.

To reproduce this issue, clone huskyCI's repository and run the following commands:
* `make install-no-pull` - Install huskyCI without pulling the security tests images.
* `make run-client` - Tries to run huskyCI on huskyCI's code
* Monitor huskyCI's MongoDB to see if `cInfo` gets changed.

**Comment by rafaveira3** [comment]
This bug occurs when [this](https://github.com/globocom/huskyCI/blob/master/api/analysis/dockerrun.go#L125) instruction is being called. I am still investigating on how to fix this.

**Comment by rafaveira3** [comment]
After reviewing this for a while, I am not able to check how we could fix this. 

I think another mega refactor in `dockerrun.go` may help to close this issue. Maybe `analysis` pointers being used are that set properly when updating in MongoDB during `dockerRunCreateContainer`. 

However, this isn't something that bad for now. I see this issue as a low priority one for now.

**Comment by rafaveira3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A bug in one of the queries to MongoDB is causing some of the fields of a securityTest to be overwritten in the database](https://trello.com/c/TAFMisfs/16-a-bug-in-one-of-the-queries-to-mongodb-is-causing-some-of-the-fields-of-a-securitytest-to-be-overwritten-in-the-database)
