### ISSUE TITLE
API: Add tests into log package

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#241]

**Comment by rafaveira3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add tests into log package](https://trello.com/c/WbOoxjDI/8-add-tests-into-log-package)

**Comment by brenol** [comment]
I can do this one. I will open a PR soon and we can proceed from there!

**Comment by rafaveira3** [comment]
Thanks, @brenol! You rock!! 🚀
