### ISSUE TITLE
Start building a huskyCI Front-End to consume database metrics

### ISSUE THREAD

**Issue by gildasio** [globocom/huskyCI#251]
Hi all, what about a front-end to HuskyCI?

Something as a dashboard just to visualize the data in huskyCI database. If it's for visualization only may be use some projects such as [Grafana](https://grafana.com/) or [Kibana](https://www.elastic.co/products/kibana) to provide this dashboard.

There is a new project on MongoDB too for provide visualization called [MongoDB Charts](https://www.mongodb.com/products/charts), in beta for now, it's seems good.

**Comment by rafaveira3** [comment]
Hey, @gildasio! Thank's for this issue and also for discussing it on our public [Gitter](https://gitter.im/globocom/huskyCI). We do have this dream of creating a front end to huskyCI soon. 🙃

I actually tried to build a new service (mongodb-chat) and add it into our `docker-compose.yml` to test it locally but failed. 

It would be great if we start working on a React FE!

**Comment by rafaveira3** [comment]
Good news! At this moment we are internally coding a React Front End to consume our `/stats` routes. When it is good enough to be open-sourced, we will create a new repository and close this issue!

**Comment by rafaveira3** [comment]
It's done: https://github.com/globocom/huskyCI-dashboard 🙃
