### ISSUE TITLE
Docker Compose version issues and error running make run-client in Ubuntu

### ISSUE THREAD

**Issue by mad-eye21** [globocom/huskyCI#256]
rishabh@ubuntu:/home/ubuntu/huskyCI# make run-client
main.go:11:2: cannot find package "github.com/globocom/huskyCI/client/analysis" in any of:
        /usr/local/go/src/github.com/globocom/huskyCI/client/analysis (from $GOROOT)
        /root/go/src/github.com/globocom/huskyCI/client/analysis (from $GOPATH)
main.go:12:2: cannot find package "github.com/globocom/huskyCI/client/config" in any of:
        /usr/local/go/src/github.com/globocom/huskyCI/client/config (from $GOROOT)
        /root/go/src/github.com/globocom/huskyCI/client/config (from $GOPATH)
main.go:13:2: cannot find package "github.com/globocom/huskyCI/client/types" in any of:
        /usr/local/go/src/github.com/globocom/huskyCI/client/types (from $GOROOT)
        /root/go/src/github.com/globocom/huskyCI/client/types (from $GOPATH)
Makefile:34: recipe for target 'build-client' failed
make: *** [build-client] Error 1

**Comment by rafaveira3** [comment]
Hey, @mad-eye21! How are you doing? I hope you're great! 

`make run-client` builds a `huskyci-client` that can be run in OSX systems, but not sure about Ubuntu ones (as I see is your case). Would you mind checking if building it manually would fix this issue? 

`make build-client-linux && ./huskyci`

**Comment by mad-eye21** [comment]
Hi, @rafaveira3 Ya I'm good.
I yesterday when it was not working so I tried it on fresh machine and got new error while installing 

ERROR: In file ./.env: environment variable name 'export CERT_PASSPHRASE' may not contains whitespace.
Makefile:54: recipe for target 'compose' failed
make: *** [compose] Error 1
![image](https://user-images.githubusercontent.com/48945491/59497025-42f12900-8eb0-11e9-98a8-20edea2f9665.png)

**Comment by rafaveira3** [comment]
Would you mind providing more details on how you got that error? 🙃 I can try to reproduce it here better building an environment just like yours. 

After running `make install` you can check your docker using `docker ps -a` to see if all containers started properly. If you see something like this you may be in the right path:
 
![image](https://user-images.githubusercontent.com/8943477/59513053-67d5a400-8e90-11e9-8879-028f16b4c9f4.png)

You can also notice that an `.env` file was generated in the root of the huskyCI file: 

```
$ cat .env
export CERT_PASSPHRASE="certPass20379178"
export HUSKYCI_CLIENT_REPO_URL="https://github.com/globocom/huskyCI.git"
export HUSKYCI_CLIENT_REPO_BRANCH="master"
export HUSKYCI_CLIENT_API_ADDR="http://localhost:8888"
export HUSKYCI_CLIENT_API_USE_HTTPS="false"
```
These environment variables are needed so huskyci-client knows which project must be checked. You must source it locally using:
```
. .env
```

Finally, you can run it in your Ubuntu machine the following command: 

```
make build-client-linux && ./huskyci
```

**Comment by mad-eye21** [comment]
Hi @rafaveira3 first of all sorry for late reply I was off for weekend.

make install is not working this is what I told, it's showing same error

root@ubuntu:/home/ubuntu/huskyCI# make install
Mode ca
Host/Clientname
Host IP
Targetdir deployments/certs
Expiration 900
Generating RSA private key, 4096 bit long modulus
......................++
...........................................................................................................................++
e is 65537 (0x10001)
Mode server
Host/Clientname dockerapi
Host IP
Targetdir deployments/certs
Expiration 365
Generating RSA private key, 4096 bit long modulus
......................................................................................++
...............................................................................................................................++
e is 65537 (0x10001)
Signature ok
subject=/CN=dockerapi
Getting CA Private Key
Mode client
Host/Clientname huskyapi
Host IP
Targetdir deployments/certs
Expiration 365
Generating RSA private key, 4096 bit long modulus
.............................................................................................++
..............................................++
e is 65537 (0x10001)
Signature ok
subject=/CN=huskyapi
Getting CA Private Key
Mode tls
Host/Clientname dockerapi
Host IP
Targetdir api
Expiration 365
Generating a 4096 bit RSA private key
...............................................................................++
.........++
writing new private key to 'api/api-tls-key.pem'
-----
ERROR: In file ./.env: environment variable name 'export CERT_PASSPHRASE' may not contains whitespace.
Makefile:54: recipe for target 'compose' failed
make: *** [compose] Error 1

**Comment by Krlier** [comment]
Hello, @mad-eye21, how are you doing?

Could you please send us the output of the following commands:
`docker version` and `docker-compose version`

**Comment by mad-eye21** [comment]
Hi @Krlier I,m good thanks.
here is output for docker version and docker-compose version

> root@ubuntu:/home/ubuntu# docker version

Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

> root@ubuntu:/home/ubuntu# docker-compose version

docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

**Comment by Krlier** [comment]
Thanks for the reply!

It seems that sourcing `.env` file at [this point](https://github.com/globocom/huskyCI/blob/master/deployments/scripts/run-create-certs.sh#L6) might be causing you trouble due to [this bug](https://github.com/docker/compose/issues/6511) from docker-compose. 

We'll need to code a little fix so huskyCI may be able to run in any `docker-compose` version.

Thanks for catching this bug, @mad-eye21! 😁

**Comment by rafaveira3** [comment]
Thanks for this tip, @Krlier!

I have just added this [Pull Request](#257) to try to fix this. Would you mind checking if it may help you, @mad-eye21?

🙃

**Comment by mad-eye21** [comment]
Thanks @Krlier @rafaveira3 for all your support I will try this with different  docker compose version.

**Comment by mad-eye21** [comment]
![image](https://user-images.githubusercontent.com/48945491/59660690-d08d8b00-91c6-11e9-8d27-45057af17702.png)
Hi @Krlier @rafaveira3  it worked with  docker compose version 1.23.2
but not with latest  docker compose versions  https://github.com/docker/compose/releases
Hope this will help to fix it.

**Comment by mad-eye21** [comment]
> 
> 
> rishabh@ubuntu:/home/ubuntu/huskyCI# make run-client
> main.go:11:2: cannot find package "github.com/globocom/huskyCI/client/analysis" in any of:
> /usr/local/go/src/github.com/globocom/huskyCI/client/analysis (from $GOROOT)
> /root/go/src/github.com/globocom/huskyCI/client/analysis (from $GOPATH)
> main.go:12:2: cannot find package "github.com/globocom/huskyCI/client/config" in any of:
> /usr/local/go/src/github.com/globocom/huskyCI/client/config (from $GOROOT)
> /root/go/src/github.com/globocom/huskyCI/client/config (from $GOPATH)
> main.go:13:2: cannot find package "github.com/globocom/huskyCI/client/types" in any of:
> /usr/local/go/src/github.com/globocom/huskyCI/client/types (from $GOROOT)
> /root/go/src/github.com/globocom/huskyCI/client/types (from $GOPATH)
> Makefile:34: recipe for target 'build-client' failed
> make: *** [build-client] Error 1

now again same issue ... :(

**Comment by rafaveira3** [comment]
That's great to hear @mad-eye21! We are having some progress here! 

Yeah, it looks like you are trying to run Mac OS huskyci-client into your Ubuntu: 🙃

```
Makefile:34: recipe for target 'build-client' failed
```

I suggest that you run the following command: 

```
. .env && make build-client-linux && ./huskyci
```

When we merge #257 we will be able to use `make run-client-linux` instead. 🙃

**Comment by mad-eye21** [comment]
it is also not working, now it is showing Makefile:38: recipe for target 'build-client-linux' failed

look at the full output 

/home/ubuntu/huskyCI# . .env && make build-client-linux && ./huskyci
main.go:11:2: cannot find package "github.com/globocom/huskyCI/client/analysis" in any of:
        /usr/local/go/src/github.com/globocom/huskyCI/client/analysis (from $GOROOT)
        /root/home/ubuntu/huskyCI/src/github.com/globocom/huskyCI/client/analysis (from $GOPATH)
main.go:12:2: cannot find package "github.com/globocom/huskyCI/client/config" in any of:
        /usr/local/go/src/github.com/globocom/huskyCI/client/config (from $GOROOT)
        /root/home/ubuntu/huskyCI/src/github.com/globocom/huskyCI/client/config (from $GOPATH)
main.go:13:2: cannot find package "github.com/globocom/huskyCI/client/types" in any of:
        /usr/local/go/src/github.com/globocom/huskyCI/client/types (from $GOROOT)
        /root/home/ubuntu/huskyCI/src/github.com/globocom/huskyCI/client/types (from $GOPATH)
Makefile:38: recipe for target 'build-client-linux' failed
make: *** [build-client-linux] Error 1

**Comment by Krlier** [comment]
Hello @mad-eye21, how are you? Thanks for the reply and for staying with us!

I ran some tests on Ubuntu to try and replicate the issue you're having and it came down to being a `$GOPATH` issue. When you first install GoLang you need to set the `$GOPATH` environment variable, which is used to specify directories outside of `$GOROOT`. This variable contains the source for Go projects and their binaries.

I suggest that you add the following line to your  `~/.bashrc`  file:
```bash
export GOPATH=$HOME/go
```
And then `source` the file, through the command:
```bash
. ~/.bashrc
```

If you have any doubts about setting this environment variable, I found [this](https://github.com/golang/go/wiki/GOPATH) guide very useful. 

Another important thing to mention is that to be able to run `GO` projects, they must be inside your `$GOPATH`. Luckily, there's an easy way to clone repositories directly to your `$GOPATH` through the command:
```go
go get github.com/globocom/huskyci
```

After successfully running this command, you should now find the `huskyCI` folder in your `$GOPATH`. Then simply run:

```sh
cd $GOPATH/src/github.com/globocom/huskyCI
```
And finally:
```sh
. .env && make build-client-linux && ./huskyci-client
```

**Comment by mad-eye21** [comment]
hey @Krlier I'm good.
Thanks I will try to do it.

**Comment by rafaveira3** [comment]
We have closed this issue as #257 was merged! Sorry! If you feel you still need any help just send us another message. 🙃

**Comment by Krlier** [comment]
@mad-eye21, I believe that we've addressed all the issues that came up here. I'm closing this Issue for now.

If you're still having any trouble running huskyCI, be sure to let us know! 😁

**Comment by mad-eye21** [comment]
Hi @Krlier @rafaveira3 
sorry for late reply I was out of town for vacation.

Ya my all issues have been solved and thanks for your support.
I was able to run huskyCI successfully
![image](https://user-images.githubusercontent.com/48945491/60094099-bfb1bc00-9768-11e9-97c6-e14d7b09e4a0.png)

but it keep going like this how to find report ?
I  am trying to scan a demo python git and given link in ..env file

export HUSKYCI_CLIENT_REPO_URL="https://github.com/uber/Python-Sample-Application.git"
export HUSKYCI_CLIENT_REPO_BRANCH="master"
export HUSKYCI_CLIENT_API_ADDR="http://localhost:8888"
export HUSKYCI_CLIENT_API_USE_HTTPS="false"

after this I used 
make run-client-linux

[HUSKYCI][*] master -> https://github.com/uber/Python-Sample-Application.git
[HUSKYCI][*] HuskyCI analysis started! asTzgqEPhmO675Arn5RApLgP54Pjvahi
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
^Cmake: *** [run-client-linux] Interrupt

I think I'm doing it wrong can you please help me how to use it.

**Comment by rafaveira3** [comment]
Hey, @mad-eye21! 

I have just followed your steps and got the expected results: 

![image](https://user-images.githubusercontent.com/8943477/60102179-9165b980-9733-11e9-9496-0abb20ab46b6.png)

To better understand what is happening in your case, I suggest that you first get huskyCI latest version by pulling master or cloning it again. 🙃

After that, if you are still having trouble, you can get a shell on the container `huskyCI_Docker_API` to see how your security tests exited: 

```sh
$ docker exec -it huskyCI_Docker_API sh
```
```sh
/ # docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
d30fd0c5790a        huskyci/retirejs    "docker-entrypoint.s…"   6 minutes ago       Exited (0) 6 minutes ago                       uber_Python-Sample-Application_master_retirejs
46b0d196497a        huskyci/bandit      "/bin/sh -c 'mkdir -…"   6 minutes ago       Exited (0) 6 minutes ago                       uber_Python-Sample-Application_master_bandit
b63f4d3999d6        huskyci/safety      "/bin/sh -c 'mkdir -…"   6 minutes ago       Exited (0) 6 minutes ago                       uber_Python-Sample-Application_master_safety
1c193860779f        huskyci/enry        "/bin/sh -c 'mkdir -…"   8 minutes ago       Exited (0) 8 minutes ago                       uber_Python-Sample-Application_master_enry
/ #
```

Additionally, you can check if huskyCI security tests images were pulled properly: 

```sh
/ # docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
huskyci/safety      latest              2d25be841226        20 hours ago        286MB
huskyci/enry        latest              b99b50be6fea        13 days ago         33.5MB
huskyci/bandit      latest              83386b7bccdc        13 days ago         285MB
huskyci/retirejs    latest              cd6ed61d93c9        13 days ago         272MB
/ #
```

You can also install [Robo 3T](https://robomongo.org/download) to view the results that are being inserted into MongoDB (local credentials can be found [here](https://github.com/globocom/huskyCI/blob/master/deployments/docker-compose.yml#L24)): 

![image](https://user-images.githubusercontent.com/8943477/60102811-c9b9c780-9734-11e9-9141-829c31695278.png)

One last option to debug your problem is to check huskyCI_API logs during the entire process (open a new tab on terminal): 

```sh
$ docker logs -f huskyCI_API
...
2019/06/25 13:21:37 {"version":"1.1","host":"251c64adea9d","short_message":"Waiting pull image... [huskyci/retirejs]","full_message":"Waiting pull image... [huskyci/retirejs]","timestamp":1561468897,"level":6,"action":"dockerPullImage","app":"huskyCI","file":"/go/src/github.com/globocom/huskyCI/api/log/log.go","info":"DOCKERRUN","line":23,"tags":"huskyCI"}
2019/06/25 13:21:39 {"version":"1.1","host":"251c64adea9d","short_message":"Container started successfully:  [d30fd0c5790ae4fe6af5242eb2e11fc4ed9d68128b067bd96ba76504580b077f]","full_message":"Container started successfully:  [d30fd0c5790ae4fe6af5242eb2e11fc4ed9d68128b067bd96ba76504580b077f]","timestamp":1561468899,"level":6,"action":"dockerRunStartContainer","app":"huskyCI","file":"/go/src/github.com/globocom/huskyCI/api/log/log.go","info":"DOCKERRUN","line":23,"tags":"huskyCI"}
2019/06/25 13:21:39 {"version":"1.1","host":"251c64adea9d","short_message":"Container started successfully:  [b63f4d3999d63c26a4d7d1d00d16906cf2a9834e1c36ddc7c541058d2aa5f12f]","full_message":"Container started successfully:  [b63f4d3999d63c26a4d7d1d00d16906cf2a9834e1c36ddc7c541058d2aa5f12f]","timestamp":1561468899,"level":6,"action":"dockerRunStartContainer","app":"huskyCI","file":"/go/src/github.com/globocom/huskyCI/api/log/log.go","info":"DOCKERRUN","line":23,"tags":"huskyCI"}
2019/06/25 13:21:39 {"version":"1.1","host":"251c64adea9d","short_message":"Container started successfully:  [46b0d196497a5d81367904a3119a4b4aa5a1e422bb2fa99e124bb74eeaf9ba57]","full_message":"Container started successfully:  [46b0d196497a5d81367904a3119a4b4aa5a1e422bb2fa99e124bb74eeaf9ba57]","timestamp":1561468899,"level":6,"action":"dockerRunStartContainer","app":"huskyCI","file":"/go/src/github.com/globocom/huskyCI/api/log/log.go","info":"DOCKERRUN","line":23,"tags":"huskyCI"}
2019/06/25 13:21:45 {"version":"1.1","host":"251c64adea9d","short_message":"Waiting pull image... [huskyci/retirejs]","full_message":"Waiting pull image... [huskyci/retirejs]","timestamp":1561468905,"level":6,"action":"dockerPullImage","app":"huskyCI","file":"/go/src/github.com/globocom/huskyCI/api/log/log.go","info":"DOCKERRUN","line":23,"tags":"huskyCI"}
2019/06/25 13:21:45 {"version":"1.1","host":"251c64adea9d","short_message":"Waiting pull image... [huskyci/safety]","full_message":"Waiting pull image... [huskyci/safety]","timestamp":1561468905,"level":6,"action":"dockerPullImage","app":"huskyCI","file":"/go/src/github.com/globocom/huskyCI/api/log/log.go","info":"DOCKERRUN","line":23,"tags":"huskyCI"}
...
```

If you're still having trouble, send us another message! 🙃

**Comment by mad-eye21** [comment]
hi @rafaveira3 

here i think image is got getting pulled properly
![image](https://user-images.githubusercontent.com/48945491/60166675-37dab900-981f-11e9-916e-7c884c7d846c.png)

**Comment by mad-eye21** [comment]
Now I got it Properly thanks for all your support.
thank you very much 
 
![image](https://user-images.githubusercontent.com/48945491/60243491-fd802300-98d5-11e9-84fc-fea363aee8e4.png)

**Comment by mad-eye21** [comment]
Hi @rafaveira3 @Krlier I have some doubt about report also can you help me with it. Please!

**Comment by rafaveira3** [comment]
Hey, @mad-eye21! Sorry for the delay in response. We have made a few changes in the huskyCI client recently. I suggest that you pull `master` again and try to perform this test again. 

The error you found on `make` means that issues were found and exit status was different than 0. This is how we fail developer CI when vulnerabilities are found. 

Feel free to ask us any other questions! We are also available at [Gitter](https://gitter.im/globocom/huskyCI).

**Comment by mad-eye21** [comment]
Thanks @rafaveira3 I just have one thing left is that the output I'm getting on screen while after running **make run-client-linux**  is there any way I can save this output (Vulnerabilities) is CSV file or JSON file I'm having difficulty to show reports.

**Comment by rafaveira3** [comment]
Yeah! I have just refactored huskyci-client so that we can output vulnerabilities in JSON. You just need to pass the argument `JSON` as `os.argv[1]` when running it:

```sh
./huskyci-client JSON
```

I have just pushed c3acabeb8f8b2b39213601b96414162567fbfc3f so that you can run the following command:

```sh
make run-client-linux-json
```

**Comment by mad-eye21** [comment]
hi @rafaveira3 Thank You so much I was waiting for this this now my DevSecOps pipeline is completed I'm adding this tool and will be giving demo to my team.

just one thing the output on screen is very align manner but not when I save it in a file

On screen output
![image](https://user-images.githubusercontent.com/48945491/61123963-4e416f80-a4c3-11e9-8735-d47f4377a68f.png)

when I save it in a file
![image](https://user-images.githubusercontent.com/48945491/61123991-6a451100-a4c3-11e9-8c88-432b1ad441c2.png)

**Comment by rafaveira3** [comment]
That's great to hear! I hope huskyCI could help your time find vulnerabilities as soon as possible. Send us feedback by creating issues or even pull requests! 🙃

If you would like to "beautify" your JSON output, you can use [jq](https://stedolan.github.io/jq/download/) and simply run:

```sh
make run-client-linux-json | jq
```

**Comment by mad-eye21** [comment]
sure Thanks again :)
