### ISSUE TITLE
HuskyCI stopped working properly in JavaScript repositories after container update

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#258]
After updating retireJS container, huskyCI stopped working properly in JavaScript repositories:
```
[HUSKYCI][ERROR] Could not Unmarshal retirejsOutput! Missing version for typescript. Need to run npm install ?
Missing version for typescript. Need to run npm install ?
Missing version for typescript. Need to run npm install ?
[{"results":[{"component":"handlebars","version":"4.1.0","
```

It would be good to check if a new JSON is now being sent to STDOUT.

**Comment by Krlier** [comment]
After some investigation, I found out that RetireJS changed its `JSON` output format to one huskyCI does not yet support.

I'm working on the output to provide a fix to this issue.
