### ISSUE TITLE
Add container version into Container struct

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#259]
This information could be consumed by huskyCI-client and output the version of the tool run by each container. It will also show to the development team if the tool is updated or not. 

Example: 

```
[HUSKYCI][*] master -> gitlab@gitlab.myorg.com:myteam/myproject.git
[HUSKYCI][*] HuskyCI analysis started! Z326oKqpemvAaI1vxO5uaAQDVyvecAB8
[HUSKYCI][!] Hold on! HuskyCI is still running...

[HUSKYCI][*] RetireJS (1.1.1) found no vulnerabilities in your JavaScript code :)
```

**Comment by Krlier** [comment]
I have an idea of how we can address this issue, we can add to `config.yml` a command to output to `cOutput` the security test version and, after that, run the actual analysis. By doing this, we would need to split the output later on and create a new database entry: `secTestVersion`.
