### ISSUE TITLE
Add yarn support for other dependencies libraries

### ISSUE THREAD

**Issue by Krlier** [globocom/huskyCI#292]
huskyCI's `config.yml` already supports other libraries added to `npm` if the `HUSKYCI_CLIENT_NPM_DEP_URL` environment variable is set, as we can see in the image below:

![image](https://user-images.githubusercontent.com/40367872/61158342-07f20d80-a4cf-11e9-80b0-f711e2065f22.png)

We should add the same support to `yarn`, maybe changing the environment variable to a better name that can fit both cases and coding a new condition to run the following command if the project has the environment variable set:

`yarn config set registry "http://registry.npm.personal/"`

After the command, we can `yarn install` normally and then run `retireJS`.

**Comment by rafaveira3** [comment]
Closing this for now as we may not be using retireJS soon as huskyCI securityTests.
