### ISSUE TITLE
Create huskyCI CLI

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#365]
It would be great if developers could run locally their repository for vulnerabilities before push their code. Example:

```sh
brew tap huskyci
```
```sh
brew install huskyci
```
```
huskyci .
```
```
[HUSKYCI][!] Severity: MEDIUM
[HUSKYCI][!] Confidence: HIGH
[HUSKYCI][!] Details: Potential file inclusion via variable
[HUSKYCI][!] File: /go/src/code/example/example/example.go
[HUSKYCI][!] Line: 76
[HUSKYCI][!] Code: os.Open(path)

[HUSKYCI][!] Severity: LOW
[HUSKYCI][!] Confidence: HIGH
[HUSKYCI][!] Details: Errors unhandled.
[HUSKYCI][!] File: /go/src/code/example2/example2/example2.go
[HUSKYCI][!] Line: 132
[HUSKYCI][!] Code: subdirs, _ := ioutil.ReadDir(p)

```

**Comment by mdjunior** [comment]
The client does not do this (with the environment variables)?

The wiki needs more documentation about the current operation of the client. With this, we can develop something similar to the tsuru client (which works locally and in a CI).

**Comment by rafaveira3** [comment]
Hey, @mdjunior. Absolutely! Our client indeed could work as our CI similar to `tsuru client`. I was wondering if we could do this check `offline` as well. Which way do you think is better for us? Would you like to help us with this one? 🙃

**Comment by mdjunior** [comment]
Is offline without connection with huskyci API?

I think doing this like the Tsuru CLI form is very interesting. I have to look at the aspects of API authentication, token generation, but I look forward to it!

**Comment by rafaveira3** [comment]
No, it's not possible at this moment doing a scan offline. 😞

Nice, it would be great to have this feature. Thanks for working on it, @mdjunior!
