### ISSUE TITLE
Add OpenID Connect Authentication

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#367]
It would be great if we add OpenID Connect authentication into huskyCI API!  

By doing so, we could allow users to login using `Github` and `Gitlab`, giving us the possibility to check which repositories a developer has acess to, profile image, and many others. 

Our [FE](https://github.com/globocom/huskyCI-dashboard) will consume this when we add a login authentication page, for instance! 🙃

**Comment by moogacs** [comment]
i would like to work on that , so ?

**Comment by rafaveira3** [comment]
Hey, @moogacs! Thanks a lot for reaching out! 🙃

I have just spoken with @mdjunior and he is currently refactoring some code that would eventually impact this issue. He will give us a further explanation about his progression so we can set a good strategy on how to work on this one. 🚀

**Comment by mdjunior** [comment]
Hey, @moogacs!

There are some challenges to make huskyci-API authenticate using OpenID Connect. At this moment I'm working refactoring the huskyci-client to make it like a familiar CLI. After this, I will implement the authentication flow at CLI.

We are using a labstack echo framework to husky-API, and you can help us to implement a middleware compatible with JWT and Husky-Tokens. You can read more about this at [echo middleware docs)[https://echo.labstack.com/middleware/key-auth].

**Comment by sagar-cs03** [comment]
Hi @mdjunior, I would like to work on this!!

**Comment by sagar-cs03** [comment]
Hi @rafaveira3, I would like to work on this :)

**Comment by rafaveira3** [comment]
Closing this one due to long inactivity.
