### ISSUE TITLE
Add Infer/Spotbugs into huskyCI

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#369]
It would be great to have [Infer](https://fbinfer.com) as a huskyCI security Test!

We have tried it before at #203! Let's hack!

**Comment by abzcoding** [comment]
@rafaveira3 what do you think about using [spotbugs](https://github.com/spotbugs/spotbugs) instead of Infer, I believe it would be easier to implement and use.

in case you agree, I would love to implement it 😉

**Comment by rafaveira3** [comment]
Hey, @abzcoding! You rock! 🔥 Absolutely! We can try `spotbugs` as well. It sounds like a great idea!

**Comment by joserenatosilva** [comment]
Hey, @abzcoding `Spotbugs` with [`find-sec-bugs`](http://find-sec-bugs.github.io/) plugin would be awesome!
