### ISSUE TITLE
Integrate huskyCI with Sonar

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#370]
It would be great to create a logic to input huskyCI output into [Sonar](https://www.sonarqube.org/). 

A good start would be looking at this JSON format from [Sonar Docs](https://docs.sonarqube.org/latest/analysis/generic-issue/).

**Comment by joserenatosilva** [comment]
I'll do this one. My idea is to generate the JSON from the Sonar docs as an output from our client.
