### ISSUE TITLE
Create a "smaller" gosec container

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#374]
```sh
# docker images -a
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
huskyci/gosec        2.0.0               22d6bdf6ea64        36 hours ago        609MB
huskyci/gosec        latest              22d6bdf6ea64        36 hours ago        609MB
```

We could find a different way to build this image using another Dockerfile rather than the one we are [currently using](https://github.com/globocom/huskyCI/blob/master/deployments/dockerfiles/gosec/Dockerfile).

**Comment by renatoaquino** [comment]
Maybe this could fix your problem:

```
FROM golang:alpine as builder

RUN apk update && apk upgrade \
	&& apk add --no-cache alpine-sdk git \
	&& apk add --update --no-cache git openssh-client jq

RUN go get github.com/securego/gosec/cmd/gosec/...

FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /go

COPY --from=builder /go/bin/gosec /go/bin/gosec
ENV PATH=/go/bin:$PATH
```

**Comment by localleon** [comment]
@renatoaquino approach would decrease the size to the following:
`
gosec                            latest              29bf5f79107c        24 seconds ago      15MB
`

I will prepare a pull request to implement this.

**Comment by renatoaquino** [comment]
https://github.com/globocom/huskyCI/pull/375

**Comment by renatoaquino** [comment]
Oops, we both did it

**Comment by localleon** [comment]
Great, and even at the exact same moment ;-)
