### ISSUE TITLE
Create a "smaller" safety container

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#377]
```sh
# docker images -a
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
huskyci/safety       latest              66548ccab2ba        36 hours ago        305MB
huskyci/safety       1.8.5               2ccbed3fe5b0        5 days ago          305MB
```

We could find a different way to build this image using another Dockerfile rather than the one we are [currently using](https://github.com/globocom/huskyCI/blob/master/deployments/dockerfiles/safety/Dockerfile).

**Comment by localleon** [comment]
Im gonna try to do this. Expect a pull request :-)
