### ISSUE TITLE
Create a "smaller" bandit container

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#378]
```sh
# docker images -a
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
huskyci/bandit       latest              96a69b020f71        36 hours ago        305MB
huskyci/bandit       1.6.0               5d820fd8f967        3 months ago        285MB
```

We could find a different way to build this image using another Dockerfile rather than the one we are [currently using](https://github.com/globocom/huskyCI/blob/master/deployments/dockerfiles/bandit/Dockerfile).

**Comment by localleon** [comment]
Because this is the same problem as #377 , the same code from #379 will work. I will prepare a pull request
