### ISSUE TITLE
Integrate HuskyCI with a relational DB

### ISSUE THREAD

**Issue by carlosljr** [globocom/huskyCI#392]
Currently, HuskyCI only supports Mongo, a non relational DB. In some environments, the usage of a relational DB is necessary due to infrastructure limitations and architecture integration with other systems. Besides, HuskyCI with a relational DB compatibility would make it more flexible and able to use in side projects.

**Comment by rafaveira3** [comment]
Hey, @carlosljr! It sounds like a great idea! Thanks a lot for this feedback. 🙃

**Comment by rafaveira3** [comment]
Closed at #422! Thanks, @carlosljr!
