### ISSUE TITLE
Make timeout configurable

### ISSUE THREAD

**Issue by igorfernandes** [globocom/huskyCI#407]
It would be great to make timeout configurable when executing the test on large repositories

**Comment by rafaveira3** [comment]
Hello, @igorfernandes! Thanks a lot for this feedback! We are considering using a `huskyci.yml` file in the root of the repository so that this type of configuration could be set. Stay tuned! 🙃

**Comment by rafaveira3** [comment]
Sup, @igorfernandes. I am closing this one for now due to long inactivity. As we are starting our hacktoberfest I will create a new issue with some guides on how others can help us reach this goal! Thanks a lot for the discussion.
