### ISSUE TITLE
Add timeout to all huskyCI's security tests

### ISSUE THREAD

**Issue by Krlier** [globocom/huskyCI#452]
Just as it was done in this [PR](https://github.com/globocom/huskyCI/pull/450), I believe it would be good if we could add the same timeout rule to all other security tests. By doing this, huskyCI would always run under a certain timeout time.

The default timeout could be set by the time needed on the average huskyCI analysis.

**Comment by rafaveira3** [comment]
Closing this one as we already have this features in huskyCI API: https://github.com/globocom/huskyCI/blob/master/api/config.yaml :)
