### ISSUE TITLE
Gitlab private repo

### ISSUE THREAD

**Issue by GabrielMioranza** [globocom/huskyCI#472]
i'm tring to run Husky in private repos, how i can add user and passwd?

**Comment by GabrielMioranza** [comment]
I used HUSKYCI_API_GIT_PRIVATE_SSH_KEY

**Comment by mkauzlar** [comment]
is this used on the client side .env?

we have set:
export HUSKYCI_CLIENT_REPO_URL="git@gitlab.com:path/to/git/repo.git"
export HUSKYCI_API_GIT_PRIVATE_SSH_KEY="/home/huskyci/.ssh/id_rsa"

however we always get: 
[HUSKYCI][ERROR] Monitoring analysis ZsEW5l2w5k8weJXronrW8qKJ8DOApW8R: huskyCI encountered an error trying to execute this analysis: error cloning
