### ISSUE TITLE
About documentation

### ISSUE THREAD

**Issue by GabrielMioranza** [globocom/huskyCI#474]
I'm tring to running husckCI inside a CentOs 8. 

- Set up a MongoDB
-Folling all steps to install docker
-Clone the project
-Run "make build" inside the project folder 

After this, how i test/run the aplication? 
I dont use tsuru

**Comment by rafaveira3** [comment]
Hey, @GabrielMioranza. Thanks for reaching out and trying to use huskyCI! 

There are a few instructions here that you can follow if you want to use it in your organization: https://huskyci.opensource.globo.com/docs/guides/install-in-my-org

Please, let me know what particular step are you having more trouble so that I can help you and update our docs!

**Comment by joserenatosilva** [comment]
Hi @GabrielMioranza. Are you trying to build an environment to use inside an organization? Or are you trying to execute it to try it out?

If you are just trying it out you could use our docker-compose file to use it locally.

If you have dedicated infrastructure to run each of huskyCI components and are trying to use huskyCI API outside a PaaS you could try a service inside your CentOs 8. It should look like:

```sh
#/etc/systemd/system/huskyCI.service
[Unit]
Description=huskyCI
After=network.target

[Service]
Type=simple
# Example of env vars, complete list: https://huskyci.opensource.globo.com/docs/api/env-vars
Environment="HUSKYCI_DATABASE_DB_ADDR=address.to.mongo.db"
Environment="HUSKYCI_DATABASE_DB_NAME=huskyci_db_name"
# make sure to make the binary executable (permissions)
ExecStart=/path/to/huskyCI/binary

[Install]
WantedBy=multi-user.target
```

You could then execute:

```sh
sudo systemctl start huskyCI
```

_Disclaimer: I didn't test this and the service file isn't complete._

**Comment by GabrielMioranza** [comment]
Desculpe a demora, estive envolvido em outros projetos. 

Eu pretendo usar o Huscky dentro da minha empresa. 

Subi uma vm com o Centos8 e dentro o Mongo, depois confesso que fiquei um pouco perdido no processo, instalei o docker e acabei não evoluindo. 

Pretendo utilizar como produção, em testes rodando localmente funcionou tudo corretamente.

**Comment by rafaveira3** [comment]
Sup, @GabrielMioranza. I am closing this one for now due to long inactivity. Fell free to reopen it if you have any other question :)
