### ISSUE TITLE
Add capabilities to scan terraform scripts

### ISSUE THREAD

**Issue by edersonbrilhante** [globocom/huskyCI#477]
Hey team,

I was thinking would be good to add TFSec as a vendor in HuskyCI. So we can look for potential vulnerabilities in TF files.

Project:
https://github.com/liamg/tfsec

Here the example:
![image](https://github.com/liamg/tfsec/raw/master/screenshot.png)

Tfsec provides an output in JSON
```
{
    "rule_id": "AWS007",
    "link": "https://github.com/liamg/tfsec/wiki/AWS007",
    "location": {
        "filename": "cluster.tf",
        "start_line": 53,
        "end_line": 53
    },
    "description": "Resource 'aws_security_group_rule.cluster_egress_internet' defines a fully open egress security group rule.",
    "severity": "WARNING"
}
```

**Comment by rafaveira3** [comment]
It sounds like a great idea, @edersonbrilhante! Would you like to work on this together? I will be very happy to review any code related to this new feature. 🙃
