### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by andrehck** [globocom/huskyCI#489]
Add the command: chmod + x create-certs.sh
before the command to create the ca.
It's not a big deal, but I think it can help.
![image](https://user-images.githubusercontent.com/54104227/83947008-c0f9be80-a7ea-11ea-82d0-1305256abb18.png)

**Comment by rafaveira3** [comment]
Sup, @andrehck! Thanks for reaching out!

What's the context of this change request? I mean, in which scenarios did you need to do this `chmod` to run this script? 

I have just run here `make install` here (that uses this file) and it worked fine without any issues!

**Comment by andrehck** [comment]
Following this application: https://huskyci.opensource.globo.com/docs/guides/install-in-my-org
I had to run chmod before creating the CA certificate.

**Comment by Krlier** [comment]
Hey, @andrehck! Thanks for contributing! 🎉 

I just added the `chmod` instruction to the documentation. You can find it here:
https://huskyci.opensource.globo.com/docs/guides/install-in-my-org

**Comment by rafaveira3** [comment]
Thanks, @andrehck and @Krlier! 🙃
