### ISSUE TITLE
Add title in HuskyCIVulnerability for new integration with DefectDojo

### ISSUE THREAD

**Issue by edersonbrilhante** [globocom/huskyCI#490]
**Description**
I would like to integrate huskyCI with [DefectDojo](https://www.defectdojo.org/). It is needed a title in DD. So instead of creating a lot of logic in the integration and possible change in each new tool added in huskyCI.  I think it would be better to add a title using information from what each tool in providing.

**Comment by rafaveira3** [comment]
Hey, @edersonbrilhante! That sounds like a great addition to huskyCI. At this moment we are only handling vuln details and no title is being used. I am looking forward to reviewing ant PR regarding this issue and very excited about having DefectDojo integration! You rock! 🚀
