### ISSUE TITLE
Typo in .huskyci example

### ISSUE THREAD

**Issue by s1mahoeg** [globocom/huskyCI#494]
The docu for an .huskyci example file contains a typo. It should be `# Safety igNOre` instead of `# Safety igONre`

https://huskyci.opensource.globo.com/docs/guides/handling-false-positives#huskyci:

```yml
[huskyCI-Ignore]

# Bandit ignore:
tests/

# Safety igonre:  <-- typo
vendor/

# Gosec ignore:
api/server.go
```

**Comment by rafaveira3** [comment]
Hello, @s1mahoeg! Thanks for the feedback! Good catch. Would you like to send us this PR or prefer that we do so? 🙃

**Comment by s1mahoeg** [comment]
Hello @rafaveira3, Is the docu also open source? I couldn't find the corresponding repository. That's why I didn't send any PR.

**Comment by rafaveira3** [comment]
Great point, @s1mahoeg! We haven't open sourced our documentation page yet! 😅  I will try to do this soon, with this typo fix done! Thanks a lot for the feedback 🙃

**Comment by rafaveira3** [comment]
hey, @s1mahoeg! We have fixed and deployed it. Sorry for the long delay. We haven't been able to open source it yet as we have some infra related code in it. Thanks once again for the report :)

**Comment by s1mahoeg** [comment]
hi @rafaveira3, no problem. Thank you :)
