### ISSUE TITLE
Support more than one internal repository at the same time

### ISSUE THREAD

**Issue by Krlier** [globocom/huskyCI#497]
<a href="https://opensource.globo.com/hacktoberfest/"><img align="right" src="https://user-images.githubusercontent.com/8943477/94613618-36e2d380-027b-11eb-8566-f8aa35ac792d.png" width="300"/></a>

## Motivation

After the changes proposed in #496, which allow huskyCI to clone and analyze Go projects with internal dependencies that don't have a `vendor` folder, it would be good if we could support more than one internal repository at the same time.

After #496, if the dependencies from an internal remote are needed, it's possible to reach it through SSH, given that the SSH key has the proper access, through the environment variables:

```
HUSKYCI_API_GIT_SSH_URL=gitlab@gitlab.example.com
HUSKYCI_API_GIT_URL_TO_SUBSTITUTE=https://gitlab.example.com/
```

## It would be great if

huskyCI could support more than one internal remote at the same time, something in line with:

```
HUSKYCI_API_GIT_SSH_URL={"gitlab@gitlab.example.com", "gitlab@gitlab.otherexample.com", "gitlab@gitlab.anotherexample.com"}
HUSKYCI_API_GIT_URL_TO_SUBSTITUTE={"https://gitlab.example.com/", "https://gitlab.otherexample.com/", "https://gitlab.anotherexample.com/"}
```

## What we expect

* Have a working solution to use multiple internal Go repositories to use in gosec securityTest.

## Tips

To better understand this problem do the following: 

* Create a Go private repository in your Github with some code to be used as a library, for example:

```go
package internal

type Student struct {
     Name string
}
```

* Create another Go project, imports this internal package (without using vendor) and save:

```go
package main

import "github.com/myuser/myproject/internal"

func main() {

     student := internal.Student{Name: "myname"}
     fmt.Println(student)

}
```

* Run gosec and see errors related to internal repositories (it will probably ask for GitHub password).
* Check how huskyCI tackles this problem in [this file](https://github.com/globocom/huskyCI/blob/master/api/config.yaml#L67).

**Comment by haardikdharma10** [comment]
Hi @Krlier, Can I fix this?

**Comment by rafaveira3** [comment]
Hello, @haardikdharma10! Absolutely! We will be very happy to review any PR related to this one. I will update this issue to use our [hacktoberfest](https://opensource.globo.com/hacktoberfest/) template soon! :)

**Comment by haardikdharma10** [comment]
Thanks @rafaveira3! Also, I'd like some help on getting started. Can you help me with the files I should start editing?

**Comment by rafaveira3** [comment]
Sure, @haardikdharma10! I have just updated this issue with our template! Check the `Tips` section for some help on how to start this one. Fell free to reach out to us if you are stuck or need any help! :)
