### ISSUE TITLE
[Proposal] Change centralized ssh key for a delegated access token

### ISSUE THREAD

**Issue by edersonbrilhante** [globocom/huskyCI#500]
Hi guys :)
I would like to propose a change in huskyci/
I think would better to delegate this responsibility to provide access to the git repo. So, we can remove in huskyci the ssh key with access to all projects. 

Example:
export 

- HUSKYCI_ACCESS_TOKEN=<token>

The huskyci client will consume this value, and pass to huskyci API and from API to the containers to clone the repo

**Comment by rafaveira3** [comment]
Hey, @edersonbrilhante! Thanks a lot for bringing to us these ideas. I totally agree with this problem of cloning all internal repositories using a single ssh key. 

A brainstorm idea that we have here is to transfer the responsibility of cloning the repository to the client itself. For instance, huskyCI may eventually receive the content of the repository in a zip file, and provide it to each security test to be run.

IMHO, to achieve that someday, we need first to code an authentication flow into huskyCI and this is something we may work on soon. Using OIDC to login with Github/Gitlab good be a great idea!

**Comment by Krlier** [comment]
Hi, @edersonbrilhante! Thanks for reaching out to us!

What you're proposing is very interesting in the sense that huskyCI would no longer need a SSH key with a very wide set of permissions! But I'm wondering what it would be like to projects with internal/private dependencies, as I'm not sure they would be reachable.

To better illustrate the issue, nowadays we need to change `GoSec`'s cloning method from `HTTPS` to `SSH`, but the same key provided to the API is used. This can only be done if the `SSH` key has access permissions to the private/internal dependency repo. We have a topic on that on our [docs](https://huskyci.opensource.globo.com/docs/guides/accessing-internal-repositories).

I believe that for your proposal to work, we'd need to find a way around that issue. What do you think?

**Comment by rafaveira3** [comment]
Hey, @edersonbrilhante! Thanks to your proposal issue we have created a new roadmap that can be found [here](https://github.com/globocom/huskyCI/projects/1)! We will create issues related to these user stories.

**Comment by rafaveira3** [comment]
Sup, @edersonbrilhante. I am closing this one for now due to long inactivity. Fell free to reopen it if you have any other question/proposal. Thanks a lot for the discussion! :)
