### ISSUE TITLE
[Proposal] Support HusckyCI on Github Actions

### ISSUE THREAD

**Issue by renanbastos93** [globocom/huskyCI#504]
I saw documentation and I remember a speaker to talk about it on GopherCon BR 2019 and only use it does Gitlab so I believe that is better we use it on Actions from Github too.

I tried to search "Husky" on the marketplace from Github then not found. 
![image](https://user-images.githubusercontent.com/8202898/89939515-70d61880-dbee-11ea-9224-e040b2e00090.png)

Let do this to use this project on Actions? Can someone talk to me about the requirements to implement it?

**Comment by Krlier** [comment]
Thanks for reaching out to us, @renanbastos93! 

Adding huskyCI to [GitHub's marketplace](https://docs.github.com/en/developers/github-marketplace) would be an awesome accomplishment! For us to be able to implement it, we might need to work on a few things first, such as user authentication, permissions, and have the client send the repository the code to be analyzed.

We've recently created a roadmap for the project, which you can find [here](https://github.com/globocom/huskyCI/projects/1) If you'd like to contribute. 🙂

I'll add your proposal to our backlog, so stay tuned for future updates and new features coming right up! 🚀

**Comment by rafaveira3** [comment]
Hey, @renanbastos93! I was at GopherCon BR 2019 presenting huskyCI, glad to hear that you were there too! 🙃 

Thanks a lot for bringing us this awesome proposal! I totally agree with it! As @Krlier mentioned, to achieve that, we have created a few tasks to have a more stable code and environment in huskyCI. A great start would be implementing authentication in our code. 

We have thought of an OIDC solution so we can log in using Github/Gitlab. Would you like to help us in this manner? We can learn and work in the same branch if desired. 😃

**Comment by renanbastos93** [comment]
> Thanks for reaching out to us, @renanbastos93!
> 
> Adding huskyCI to [GitHub's marketplace](https://docs.github.com/en/developers/github-marketplace) would be an awesome accomplishment! For us to be able to implement it, we might need to work on a few things first, such as user authentication, permissions, and have the client send the repository the code to be analyzed.
> 
> We've recently created a roadmap for the project, which you can find [here](https://github.com/globocom/huskyCI/projects/1). You can help us by giving a hand in this [card](https://github.com/globocom/huskyCI/projects/1#card-43275128). 🙂
> 
> I'll add your proposal to our backlog as a card, so stay tuned for future updates and new features coming right up! 🚀
> Link to the card: https://github.com/globocom/huskyCI/projects/1#card-43488306

How cool, thanks for your attention.
I will happy to help you.

**Comment by renanbastos93** [comment]
> Would you like to help us in this manner? We can learn and work in the same branch if desired.

how nice,

Well, first I need to study more about OIDC. Can you send some links about it?
Another detail, when you spoke working in the same branch is pair programming?

**Comment by rafaveira3** [comment]
Hey, @renanbastos93! I am so sorry for the long delay on this one. I was on vacation for a few days! :P We are currently working on a few issues for our [Hacktoberfest](https://opensource.globo.com/hacktoberfest)!

This one related to Auth can be found here! https://github.com/globocom/huskyCI/issues/507

I am closing this one for now as this is a huge epic we will reach in the future by delivering all the features related to our [roadmap](https://github.com/globocom/huskyCI/projects/1). 

I will be very happy to review any Pull Request if you like to help us improve huskyCI, @renanbastos93 😊🚀
