### ISSUE TITLE
Add OAuth2 login functionality into cobra CLI

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#507]
<a href="https://opensource.globo.com/hacktoberfest/"><img align="right" src="https://user-images.githubusercontent.com/8943477/94613618-36e2d380-027b-11eb-8566-f8aa35ac792d.png" width="300"/></a>

## Motivation

To have features like vulnerability management (and many others), we need to have some kind of authentication in huskyCI. 

If we have a CLI command that will log in users using Github and Gitlab, for instance, we will have the possibility to check which repositories a developer has access to, profile image, and many others. 

## It would be great if

We have an OAuth2 solution coded in our [CLI](https://github.com/globocom/huskyCI/tree/master/cli) by implementing a [cobra](https://github.com/spf13/cobra) command `login`.

## What we expect

By typing the following command, huskyCI must be able to redirect the authorization request to an OAuth2 provider (Github? ❤️) open a web browser for the user to complete the login, and store the token into a file `.huskyci` to be used later on.

```sh
$ huskyci login
Successfully logged in!
```

## Tips

* [Gsh already does something similar](https://github.com/globocom/gsh/blob/master/cli/cmd/login.go)  
* [Tsuru already does something similar as well](https://github.com/tsuru/tsuru/blob/master/cmd/oauth.go) 
* [Authorizing OAuth Apps - Github](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/)

**Comment by lzakharov** [comment]
I would like to take it up! I think to use the [device flow](https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps#device-flow) for the authorization and I need to know the client id (for the first time I can create my own GitHub App).
