### ISSUE TITLE
Have securityTests run in Kubernetes

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#510]
<a href="https://opensource.globo.com/hacktoberfest/"><img align="right" src="https://user-images.githubusercontent.com/8943477/94613618-36e2d380-027b-11eb-8566-f8aa35ac792d.png" width="300"/></a>

## Motivation

huskyCI runs all its securityTests using a Docker API component. It works fine but some companies may eventually face some problems when scaling to multiple VMs running this component. 

By adding a load balancer, for instance, huskyCI has no logic to understand which VM behind it should query to check if a particular securityTest has finished.

## It would be great if

We add a new component to huskyCI that uses k8s to run our securityTests containers. If a company uses [Rancher](https://rancher.com/), this process of running containers can be used as a service, for example.

## What we expect

This one can be tricky because a few refactoring in [securitytest package](https://github.com/globocom/huskyCI/tree/master/api/securitytest) is needed. However, we will be very happy if we have an interface in it so that companies choose which best fits their environment.

## Tips

* [Golang Lib 1 to talk with k8s](https://github.com/kubernetes/client-go)
* [Go by Example: Interfaces](https://gobyexample.com/interfaces)

**Comment by rogeriobastos** [comment]
Hi, is there any WIP related to this feature. I am interested in work on it.

**Comment by fguisso** [comment]
It’s working in branch main.
