### ISSUE TITLE
Add cache in the API to better serve the huskyCI Dashboard

### ISSUE THREAD

**Issue by Krlier** [globocom/huskyCI#513]
<a href="https://opensource.globo.com/hacktoberfest/"><img align="right" src="https://user-images.githubusercontent.com/8943477/94613618-36e2d380-027b-11eb-8566-f8aa35ac792d.png" width="300"/></a>

## Motivation

As more and more teams are adding huskyCI to their pipelines and the data present in the database grows, we've been noticing some increase in the loading time for [huskyCI-dashboard](https://github.com/globocom/huskyCI-dashboard), which might not be the best for user experience.

## It would be great if

We have a caching solution implemented in huskyCI's API to allow for faster response and loading times.

## What we expect

* A working caching solution for the following routes:
```
<huskyCIAPIAddress>/stats/author
<huskyCIAPIAddress>/stats/analysis
<huskyCIAPIAddress>/stats/language
<huskyCIAPIAddress>/stats/container
<huskyCIAPIAddress>/stats/repository
<huskyCIAPIAddress>/stats/historyanalysis
<huskyCIAPIAddress>/stats/severity
```

* Local cache is a good start (Redis is not necessary! Go Mutex is a great choice!) 

## Tips

* [Golang Local cache](https://hackernoon.com/dancing-with-go-s-mutexes-92407ae927bf)

**Comment by lzakharov** [comment]
I would like to take it up!
