### ISSUE TITLE
Documentation: Usage on windows

### ISSUE THREAD

**Issue by billionai** [globocom/huskyCI#522]
I couldn't find anything on the docs about how to set up a local environment on windows. 

Also, in the same ocal environment page, there's no information on what is or how to get the HUSKYCI_CLIENT_TOKEN.

**Comment by Krlier** [comment]
Hi, @billionai! Thanks for reaching out to us.

Our documentation does, indeed, not yet feature a Windows local environment setup. We'll be working on it soon, stay tuned!

When it comes to the `HUSKYCI_CLIENT_TOKEN`, it's currently being developed and is entirely optional. When running huskyCI you can leave it out for now.

**Comment by Krlier** [comment]
Hi, @billionai! I'm closing this issue due to its long inactivity.

If you need any more information regarding this question, feel free to reopen this issue or to create a new one!
