### ISSUE TITLE
Having trouble getting private repos up and running with docker for mac

### ISSUE THREAD

**Issue by katebygrace** [globocom/huskyCI#532]
Heya! I'm having trouble getting HuskyCI running on private repos. It works great on public ones (and was humbling on a script I thought was pretty simple, thanks!) 

I've got the following environment variables: 
export HUSKYCI_CLIENT_REPO_URL="https://github.com/katebygrace/laundry.git"
export HUSKYCI_CLIENT_REPO_BRANCH="master"
export HUSKYCI_CLIENT_API_ADDR="http://localhost:8888"
export HUSKYCI_CLIENT_API_USE_HTTPS="false"
export HUSKYCI_CLIENT_TOKEN="token"
export HUSKYCI_API_GIT_PRIVATE_SSH_KEY=`cat ~/.ssh/id_rsa`

(token i figured would be best omitted) 
When I run `make run-client` with the exact same repo and i make the repo public, it works! 
But when i run it after making the repo private, it fails on this error: 

[HUSKYCI][*] master -> https://github.com/katebygrace/laundry.git
[HUSKYCI][*] huskyCI analysis started! xyex7EqBwwHEYUd7ebC8Dw90SAIFfgRh
[HUSKYCI][ERROR] Monitoring analysis xyex7EqBwwHEYUd7ebC8Dw90SAIFfgRh: huskyCI encountered an error trying to execute this analysis: error cloning
make: *** [run-client] Error 1

Seems like the private key isn't syncing up to the container. I think I'm missing something on my end, but not sure what. I'd love to run this on my work CI and was using my home lab to test, and got this far. Got any suggestions? Thanks! 

Edit to add a few things I did try 
`source .env` (every time after editing .env) 
re-running `make-install`, which blew away the variables I had and I had to put mine back 
echoing the variables in my terminal - worked 
echoing the variables in the docker container - did not work (yielded nothing) 
making the huskyci_api_git_private_ssh_key in " quotations instead of ` 
trying without the private SSH key 

anyway let me know what I need to update! I'm sure its something environment/config related I'm missing and probably user error, but I'd love to get this up and running :)

**Comment by fguisso** [comment]
You need to use the ssh url in repo_url, this way the api will understand that you have an ssh key to access the code.
