### ISSUE TITLE
Verify if image exists and get image if it doesn't exist

### ISSUE THREAD

**Issue by carlosljr** [globocom/huskyci#81]
The images used in Docker to start the containers with security tests is downloaded once from Vagrant script. However, image management must be done on the API. If the images are removed from Docker, the security tests will fail. 

The HuskyCI API needs to know if images that deal with security tests exist and, if not, get from the correspondent registry. After that, the logic follows the current procedure.

**Comment by rafaveira3** [comment]
This issue was closed in #107 😃
